name: "rose_chess"
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  ffi: ^2.1.3
  dio: ^5.7.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  flutter_svg: ^2.0.16
  drift: ^2.22.1
  drift_flutter: ^0.1.0
  get_it: ^8.0.3
  toastification: ^2.3.0
  syncfusion_flutter_charts: ^28.1.37
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
  intl_utils: ^2.8.7
  drift_dev: ^2.22.0
  build_runner: ^2.4.13

  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/xiangqiboards/
    - assets/images/xiangqipieces/wikipedia/
flutter_intl:
  enabled: true  
  class_name: AppLocalizations                
  main_locale: en              
  arb_dir: lib/l10n                
  output_dir: lib/generated     
  use_deferred_loading: false  

flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "assets/icons/favicon.512x512.png" 

android:
  useAndroidX: true
  compileSdkVersion: 33
  targetSdkVersion: 33
  minSdkVersion: 21 

requestPermissions: true